name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  use-template:
    uses: jluiscortes/template-back-end/.github/workflows/ci-cd-template.yml@main
    with:
      node-version: "18.x"
      app-name: "example-backend"
